name: Terraform Deploy
on: 
  # push: 
  #   branch : [main]
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.ACESSKEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.SECRETKEY}}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform plan
        run: terraform plan


  terraform-Create:
    runs-on: ubuntu-latest
    needs: terraform
    environment: Dev
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.ACESSKEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.SECRETKEY}}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform plan
        run: terraform plan
      - name: Terraform Apply
        run: terraform apply --auto-approve

      #Connect EC2 Via SSH, Install and run the python
      - name: Connecting To EC2
        run: |
          echo "${{secrets.SSHKEY}}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@$(terraform output -raw public_ip) << 'EOF'
          sudo yum install -y git
          sudo yum install -y python3-pip
          sudo pip3 install virtualenv

          cd /opt
          git clone https://github.com/dharmaparasa/FrontendBackend.git
          cd /opt/FrontendBackend/backend

          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          cat <<EOF > /etc/systemd/system/myapp.service
          [Unit]
          Description=My Python App
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/opt/FrontendBackend/backend
          EnvironmentFile=/etc/myapp.env
          ExecStart=/opt/FrontendBackend/backend/venv/bin/python app.py
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target
          EOF

          systemctl daemon-reexec
          systemctl daemon-reload
          systemctl enable myapp
          systemctl start myapp

